name: smart_baby_guard
description: "Smart Temperature Guard companion app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_bluetooth_serial: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  file_picker: ^8.0.3
  just_audio: ^0.9.38
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  min_sdk_android: 23
  adaptive_icon_background: "#1A237E"
  adaptive_icon_foreground: assets/icon/icon.png
